# Generated by Django 4.0.4 on 2022-04-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=18)),
                ('profession', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Workers',
                'verbose_name_plural': 'My Workers',
            },
        ),
    ]
